# Generated by Django 3.2 on 2023-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
